services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=aa6250ea069e34fa6e787a3dd8f13e77
      - DATABASE_HOST=db
      - DATABASE_USERNAME=rails
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=votings

    volumes:
      - .:/rails
    depends_on:
      - db
  db:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=rails
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=votings
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: